# Generated by Django 4.1.3 on 2023-06-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_chambres', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('capacite', models.PositiveIntegerField()),
                ('occupee', models.BooleanField(default=False)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enregistrement.chambre')),
            ],
        ),
    ]
