# Generated by Django 4.1.3 on 2023-06-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0002_etudiant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='capacite',
        ),
    ]
